### ISSUE TITLE
exposing query results as Observable [important !!!!]

### ISSUE THREAD

**Issue by djleonskennedy** [Breeze/breeze.bridge.angular#11]
I'm using `ngrx/store` with `ngrx/effects`, i'm MUST use Observable's and this code is not work

```
import {Injectable} from '@angular/core';
import {Http} from '@angular/http';
import {EntityManager, EntityQuery} from 'breeze-client';
import {Observable} from 'rxjs';
import {User} from "../models/User";

@Injectable()
export class FetchAPIService {
  private em: EntityManager;

  constructor(private http: Http) {
    this.em = new EntityManager("breeze/data");
  }

  public getUser(id): Observable<User> {

    const query = EntityQuery
      .from("Users")
      .where('system_user_id', 'eq', id);
    
     return new Observable(observer => {
      this.em.executeQuery(query)
        .then((user: any) => {
          const _user: User = _.get(user, 'results[0]', null);
          observer.next(_user);
          observer.complete();
        })
        .catch(e => observer.error(e));
     })
  }
}
```

Effect

```
@Injectable()
export class UserEffects {
  constructor(private actions$: Actions, private api: FetchAPIService) { }

  @Effect() getUser$: Observable<Action> = this.actions$
    .ofType(user.ActionTypes.FETCH_USER)
    .switchMap(action =>
      this.api.getUser(action.payload)
        .map((u: User) => new user.UserFetchSuccessAction(u))
        .catch(err => of(new user.UserFetchFailAction(err)))
    )
}
```

if i use `Http` (angular2) or even `setTimeout` all work's fine, 
but with Breeze `no`

if it adapted to angular2 it should support Observable

Could you suggest any workarounds ?

Thank you

**Comment by steveschmitt** [comment]
Does the line
`     const _user: User = _.get(user, 'results[0]', null);`
give the the correct value?

**Comment by djleonskennedy** [comment]
Yes it extract user payload

**Comment by marcelgood** [comment]
It really doesn't matter at the moment that Breeze returns Promises. An Observable makes sense if you need to cancel a request or if you expect a stream of values. Neither is the case with Breeze. Breeze currently doesn't support canceling a query. There are reasons for that. Similarly, a breeze query only ever returns one response or an error. So, there are no benefits at the moment to using Observables.

If you need an Observable upstream in your code, then simply use `Observable.fromPromise()` to turn the Promise you get from Breeze into an Observable. You can do the same thing with an Observable and turn it into a Promise with the `toPromise` operator. In most cases, Observables and Promises are interchangeable. There are cases where Observables make more sense than Promises, but not in the case of Breeze, at least in its current form.

**Comment by AndriiDidkivsky** [comment]
Absolutely agree with @djleonskennedy

**Comment by steveschmitt** [comment]
Does `Observable.fromPromise()` work for you?

**Comment by marcelgood** [comment]
I want to reiterate that it is very unlikely that Breeze will switch to Observables anytime soon. It really isn't necessary at this point. There is nothing in Angular 2 that says you must use Observables. As I said they make a lot of sense for certain scenarios, but as far as Angular 2 is concerned, Promises and Observables stand on equal footing. 

Angular 2 itself accepts either a Promise or an Observable everywhere. Things like the AsyncPipe, Router guards etc. all accept a Promise or an Observable. 

The real issue here is `ngrx/store` and `ngrx/effects`. They should be coded to accept either a Promise or an Observable just like Angular does. It's not the job of low level I/O libraries such as Breeze to support both. The consumer of an async operation should accept both, not the producer, but if that's not the case as I said you can turn one into the other with `Observable.fromPromise()` and the `toPromise` operator.

**Comment by marcelgood** [comment]
Just a quick update. You may run into a compiler error if you try to use `Observable.fromPromise()`. That's because the Breeze type definitions use their own promise interface that has a `finally` method. Some promise implementations such as Q support the `finally` method. I've just pushed a change to the type definitions that fixes that. It'll be in the next release, but in the meantime you can just cast to `any` to get past the error. So, your example from above would look like this.

```
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { EntityManager, EntityQuery } from 'breeze-client';
import { Observable } from 'rxjs';
import { User } from "../models/User";

@Injectable()
export class FetchAPIService {
    private em: EntityManager;

    constructor(private http: Http) {
        this.em = new EntityManager("breeze/data");
    }

    public getUser(id: any): Observable<User> {

        const query = EntityQuery
            .from("Users")
            .where('system_user_id', 'eq', id);

        return Observable.fromPromise(
            <any>this.em.executeQuery(query).then(data => {
                return <User>data.results[0] || null;
            })
        );
    }
}
```

**Comment by djleonskennedy** [comment]
@marcelgood Thats works, thank you!
