### ISSUE TITLE
Angular 2 - added to imports breaking?

### ISSUE THREAD

**Issue by ganySA** [Breeze/breeze.bridge.angular#6]
A couple of days ago ionic2 project decided to change from webpack to rollup.js and also move to the final version of angular (ngModule)

In summary its been a nightmare to get external libs working but with hacking small bits here and there i have managed to get the other libs i have moment/lodash working. What i have failed to do is get breeze / angular bridge working.

I have included the latest version of breeze angular bridge but i am getting an error:

Any ideas?

```
error_handler.js:45 EXCEPTION: Uncaught (in promise): Error: Q is undefined. Are you missing Q.js? See https://github.com/kriskowal/qErrorHandler.handleError @ error_handler.js:45next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3r @ polyfills.js:3i @ polyfills.js:3invoke @ polyfills.js:3
error_handler.js:50 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:50next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64t.handleError @ polyfills.js:3e.runGuarded @ polyfills.js:3r @ polyfills.js:3i @ polyfills.js:3invoke @ polyfills.js:3
error_handler.js:51 Error: Uncaught (in promise): Error: Q is undefined. Are you missing Q.js?
```

**Comment by ganySA** [comment]
Hi 

Further to the above - looked a the demo you guys have created for Angular 2 (thank you for this great point of reference) I had not put AngularBridge into the import section.

After adding this to the imports section the error is different and the following line fails:

```
breeze_client_1.config.initializeAdapterInstance('modelLibrary', 'backingStore', true);

Unhandled Promise rejection: Unregistered adapter.  Interface: modelLibrary AdapterName: backingStore ; Zone: <root> ; Task: Promise.then ; Value: Error: Unregistered adapter.  Interface: modelLibrary AdapterName: backingStore(…) Error: Unregistered adapter.  Interface: modelLibrary AdapterName: backingStore

```

**Comment by marcelgood** [comment]
Yes, as you probably know by now, commonjs/umd libraries need special considerations with rollup.js. I made a change in Breeze 1.5.12 trying to accommodate rollup.js, but ended up rolling it back in 1.5.13 and deprecating 1.5.12, because it was breaking existing projects. So, first of all make sure you are using 1.5.13.

The issue with Breeze and rollup.js is that you can't use breeze.debug.js, because of the bundled adapters. Rollup.js doesn't support modules that import themselves, which is what's the case in breeze.debug.js, so you must use breeze.base.debug.js.

The way to instruct rollup.js to use breeze.base.debug.js is by using the strict alias plugin and set up an alias for breeze-client in your rollup configuration.

```
  plugins: [
      alias({
          'breeze-client': path.resolve(__dirname, 'node_modules', 'breeze-client/breeze.base.debug.js')
      }),
```

But, now, because we no longer automatically load and configure the Breeze adapters out of the box, you have to manually import and configure them. See in the example here: https://github.com/Breeze/temphire.angular2/blob/master/TempHire/app/core/services/entity-manager-provider.ts

```
// Import breeze adapters
import 'breeze-client/breeze.dataService.webApi';
import 'breeze-client/breeze.modelLibrary.backingStore';
import 'breeze-client/breeze.uriBuilder.json';
import 'breeze-client/breeze.uriBuilder.odata';

config.initializeAdapterInstances({ dataService: 'webApi', uriBuilder: 'odata' });
```

Make sure you don't make the `config.initializeAdapaterInstances` call too early. It needs to be done after Angular 2 has bootstrapped. These may not be the correct adapters for your project and normally you only need to import one of the uriBuilders, depending on your backend. The example works with two different backends and it configures the correct uriBuilder depending on the backend. You do need the backingStore modelLibrary, because that's what the breeze angular 2 bridge uses, but you don't have to configure it yourself. The bridge takes care of that. That's the reason for your error above.

Breeze needs further special considerations while running it through the commonjs plugin. Because of the kind of universal module header that Breeze uses, rollup.js can't see the named exports, so you have to list all the named exports that your application uses. 

```
      commonjs({
        include: [
            'node_modules/rxjs/**', 
            'node_modules/breeze-client/**', 
            'node_modules/breeze-bridge-angular2/**', 
            'node_modules/lodash/**'
        ],
        exclude: [
            'node_modules/breeze-client/breeze.debug.js'
        ],
        namedExports: {
            'node_modules/breeze-client/breeze.base.debug.js': [
                'core',
                'config',
                'NamingConvention',
                'DataService',
                'EntityManager',
                'EntityQuery',
                'FetchStrategy',
                'SaveOptions'
            ]
        }
      }),
```

You can see the complete rollup.js configuration here: https://github.com/Breeze/temphire.angular2/blob/master/TempHire/rollup.js

**Comment by ganySA** [comment]
Thank you for this comprehensive answer. I am going to have to give it a try - hope i can get it working.

Do you by any chance know what uriBuilder i should be using for a .net web breeze api?

**Comment by ganySA** [comment]
@marcelgood : Hi marcel i have just put in your code to my app. The instructions are marvelous and my app is now working as expected. 

Thanks again for your help - i hope this code helps something else.

**Comment by marcelgood** [comment]
Great! Thanks for confirming. To answer your question, for the .NET WebApi Breeze server you need the odata uriBuilder.
